### ISSUE TITLE
📈 improve card background color for better contrast

### ISSUE THREAD

**Issue by JLS-DEV-lab** [Slynite/website#31]
**Is your feature request related to a problem? Please describe.**
It's just hard to recognize the contrast between the website background and cards

**Describe the solution you'd like**
A lighter color would be nice.

**Comment by D3nn7** [comment]
Which color should be used for this? Please make a suggestion.

**Comment by D3nn7** [comment]
We want to use '#1a1a1a' as new color.

**Comment by D3nn7** [comment]
Implemented in [PR62](https://github.com/Slynite/website/pull/62).
